back-end/railsApp/Assignment-app/config/routes.rb
Rails.application.routes.draw do

  get '/user/new' => 'users#new', as: :user_new
  post '/user' => 'users#create', as: :user_create
  get '/users/list' => 'users#index', as: :users_list
  get '/user/:id/edit' => 'users#edit', as: :user_edit
  put '/user/:id/edit' => 'users#update',as: :user_update
  get '/user/:id/show' => 'users#show', as: :user_show
  delete '/user/:id' => 'users#destroy', as: :user_destroy
  get '/user/profile' => 'users#profile',as: :user_profile

  get '/project/new' => 'projects#new',as: :project_new
  post '/project' => 'projects#create', as: :project_create
   get '/projects/list' => 'projects#index', as: :projects_list

end

back-end/railsApp/Assignment-app/app/models/project.rb
class Project < ActiveRecord::Base
end

back-end/railsApp/Assignment-app/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password_encrypt
  before_save :encrypt_password
  
  validates :firstname,presence: true 
  validates :lastname,presence:  true 
  validates :email,presence:  true 
  # validates :password,presence:  true,:format => {:with => /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[^\w\s]).{8,}$/, message: "must be at least 8 characters and include one number one letter and one uppercase"}
  # validates :firstname,:lastname,:email,:password, :length => {:minimum => 2}
  validates_format_of :password,on: :create, :with => /[A-Z]/,:message=>'must have atleast 1 uppercase letter'
  validates_format_of :password,on: :create,:with => /[a-z]/,:message=>'must have atleast 1 lowercase letter'
  validates_format_of :password,on: :create,:with => /[0-9]/,:message=>'must have atleast one digit'  
  validates_format_of :password,on: :create, :with => /[`~!@#$%^&*()_+=-]/,:message=>'must have atleast one special character'
  validates :email, :presence => true,on: :create,:uniqueness => {:case_sensitive => false},format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, message: "Not a valid email Address" }

  def encrypt_password
    if true
      self.password = BCrypt::Engine.generate_salt
      self.password = BCrypt::Engine.hash_secret(password_encrypt,password)
    end
  end
end

back-end/railsApp/Assignment-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

back-end/railsApp/Assignment-app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@project=Project.new
	end
	 def create
	 	# binding.pry
	 	@project=Project.new(project_params)

	 	 @Project.save
	 	redirect_to projects_list_path
	
	 end

	 def index
	 	@projects=Project.all
	 end
	  private

	 def project_params
	 	params.require(:project).permit(:name,:duration,:teamsize,:cost,:domain)
	 end

end

back-end/railsApp/Assignment-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user=User.new
	end
	 def create
	 	# binding.pry
	 	@user=User.new(user_params)

	 	if @user.save
	 	redirect_to users_list_path
	 else
	 	render "new"
	 end
	 end

	 def index
	 	@users=User.all
	 end

	 def edit
	 	@user=User.find_by_id(params[:id])
	 end

	 def update
	 	# binding.pry
	 	@user=User.find_by_id(params[:id])
	 	if @user.update_attributes(user_params)
	 	redirect_to users_list_path
	 else
	 	render "edit"
	 end
	 end

	 def show
	 	@user=User.find_by_id(params[:id])
	 end

	 def destroy
	 	@user=User.find_by_id(params[:id])
	 	@user.destroy
	 	redirect_to users_list_path
	 end

	 def profile
	 	@users=User.all
	 end

	 def projectnew
	 	@project=Project.new
	 end

	 



	 private

	 def user_params
	 	params.require(:user).permit(:firstname,:lastname,:email,:password)
	 end



end

back-end/railsApp/Assignment-app/app/helpers/application_helper.rb
module ApplicationHelper
end

back-end/railsApp/Assignment-app/app/helpers/projects_helper.rb
module ProjectsHelper
end

back-end/railsApp/Assignment-app/app/helpers/users_helper.rb
module UsersHelper
end

back-end/railsApp/Assignment-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssignmentApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

back-end/railsApp/Assignment-app/app/views/projects/index.html.erb
<h1>Listing Projects</h1>
<table border=1>
<tr>
<th> Name</th>
<th>Duration</th>
<th>Team Size</th>
<th>Cost</th>
<th>Domain</th>
<!-- <th>Password</th> -->
</tr>

<% @projects.each do |p|%>
<tr>
<td><%= p.name%></td>
<td><%= p.duration%></td>
<td><%= p.teamsize%></td>
<td><%= p.cost%></td>
<td><%= p.domain%></td>
</tr>
<%end%>
</table></br>

back-end/railsApp/Assignment-app/app/views/projects/new.html.erb
 <h1>Enter Details</h1>

 <%= form_for @project, url: project_create_path do |f| %>

 


 <p>
 <h2 style="font-style:italic">Enter Name:<%= f.text_field :name %></br></br></h2></p>
 <p>
 <h2 style="font-style:italic">Enter Duration:<%= f.text_field :duration %></br></br></h2></p>
 <p>
 <h2 style="font-style:italic">Enter Team Size:<%= f.text_field :teamsize %></br></br></h2></p>
 <p>
 <h2 style="font-style:italic">Enter Cost:<%= f.password_field :cost%></br></br></h2></p>
 <p >
 <p>
  <h2 style="font-style:italic">Enter Cost:<%= f.password_field :domain%></br></br></h2></p>

 <%= f.submit :submit%>
 <%end%>

back-end/railsApp/Assignment-app/app/views/users/edit.html.erb
 <h1>Edit Users</h1>
<body bgcolor="chocolate">
<%= form_for @user, url:user_edit_path(@user),method: :put  do |f| %>
<p><h2 style="font-style:italic">

 First Name:<%= f.text_field :firstname %></br></br></h2></p>
<p><h2 style="font-style:italic">
 Last Name:<%= f.text_field :lastname %></br></br></h2></p>
<p><h2 style="font-style:italic">
 Email:<%= f.text_field :email %></br></br></h2></p>

 <%= f.submit :submit%></p>
 
 <% end%>
 </body>

back-end/railsApp/Assignment-app/app/views/users/index.html.erb
<h1>Listing Users</h1>
<table border=1>
<tr>
<th>First Name</th>
<th>LastName</th>
<th>Email</th>
<!-- <th>Password</th> -->
</tr>

<% @users.each do |u|%>
<tr>
<td><%= u.firstname%></td>
<td><%= u.lastname%></td>
<td><%= u.email%></td>

<td><%= link_to 'Edit',user_edit_path(u) %></td>
<td><%= link_to 'Destroy',user_destroy_path(u),method: :delete,data: {confirm:'Are you sure?'} %></td>


</tr>
<%end%>
</table></br>

<%= link_to 'Projects',projects_list_path %>

back-end/railsApp/Assignment-app/app/views/users/new.html.erb
 <h1>Enter Details</h1>
<body bgcolor="lightgreen">
 <%= form_for @user, url: user_create_path do |f| %>

 <%if @user.errors.any? %>
 <!-- <div id="errorExplaination"> -->

 <h2><%pluralize(@user.errors.count,"error") %>Prohibited this user from being saved</h2>
 <ul>
 <% @user.errors.full_messages.each do |msg|%>
 <li><%= msg%></li>
 <%end%>
 </ul>
 <!-- </div> -->
 <% end %>


 <p>
 <h2 style="font-style:italic">Enter FirstName:<%= f.text_field :firstname %></br></br></h2></p>
 <p>
 <h2 style="font-style:italic">Enter Lastname:<%= f.text_field :lastname %></br></br></h2></p>
 <p>
 <h2 style="font-style:italic">Enter Email:<%= f.text_field :email %></br></br></h2></p>
 <p>
 <h2 style="font-style:italic">Enter Password:<%= f.password_field :password%></br></br></h2></p>
 <p ><%= f.submit :submit%></p>
 <%end%>
 </body>

back-end/railsApp/Assignment-app/app/views/users/profile.html.erb
<h1>Listing Users</h1>
<table border=1>
<tr>
<th>First Name</th>
<th>LastName</th>
<th>Email</th>
<!-- <th>Password</th> -->
</tr>

<% @users.each do |u|%>
<tr>
<td><%= u.firstname%></td>
<td><%= u.lastname%></td>
<td><%= u.email%></td>
<td><%= link_to 'Edit Update',user_edit_path(u) %></td>

</tr>
<%end%>
</table>

back-end/railsApp/Assignment-app/app/views/users/show.html.erb
<h1>Show User Record</h1>

<table>
<tr>
<th>First Name</th>
<th>Last Name</th>
<th>Email</th>
<th>Password</th>
</tr>


<tr>
<td><%= @user.firstname%></td>
<td><%= @user.lastname%></td>
<td><%= @user.email %></td>
<!-- <td><%= @user.Password %></td> -->
</tr>

</table>